### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by PavelInt** [InfinityRaider/AgriCraft#116]
[10:20:57] [Client thread/ERROR]: Unable to parse metadata from agricraft:textures/blocks/seedAnalyzer.png
java.lang.RuntimeException: broken aspect ratio and not an animation
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147964_a(TextureAtlasSprite.java:273) ~[bqd.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:228) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:123) [bpz.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94) [bqf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:200) [bqf.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) [brg.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) [brg.class:?]
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
	at com.mumfrey.liteloader.client.GameEngineClient.refreshResources(GameEngineClient.java:62) [GameEngineClient.class:1.7.10_04]
	at com.mumfrey.liteloader.client.ClientEvents.onStartupComplete(ClientEvents.java:236) [ClientEvents.class:1.7.10_04]
	at com.mumfrey.liteloader.client.CallbackProxyClient.onStartupComplete(CallbackProxyClient.java:48) [CallbackProxyClient.class:1.7.10_04]
	at com.mumfrey.liteloader.core.event.EventProxy.$event00000(EventProxy.java:211) [EventProxy.class:1.7.10_04]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:573) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[10:20:57] [Client thread/ERROR]: Using missing texture, unable to load missing_icon_block_758_agricraft:textures/blocks/waterChannel.png, java.io.FileNotFoundException

**Comment by InfinityRaider** [comment]
Optifine?

**Comment by Pilad** [comment]
Yes.Optifine )))

**Comment by InfinityRaider** [comment]
Not going to bother with that one, sorry
