### ISSUE TITLE
Harvestcraft Candleberries cause internal server error

### ISSUE THREAD

**Issue by bogatyr-n** [InfinityRaider/AgriCraft#304]
Attempting to harvest a candleberry crop causes the following error.

```
java.lang.NullPointerException
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:59) ~[xk.class:?]
	at net.minecraft.block.Block.func_149642_a(Block.java:681) ~[aji.class:?]
	at com.InfinityRaider.AgriCraft.blocks.BlockCrop.harvest(BlockCrop.java:132) ~[BlockCrop.class:?]
	at com.InfinityRaider.AgriCraft.blocks.BlockCrop.func_149727_a(BlockCrop.java:209) ~[BlockCrop.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by InfinityRaider** [comment]
Thanks for the report. WIll fix

**Comment by InfinityRaider** [comment]
Its because theyre not correctly registered to the oredictionary, I've added a null check now, so harvesting them will do nothing.
You will however have to bug Pam to register the candleberries as "cropCandleberry" instead of "cropCandle".
