### ISSUE TITLE
[crash] registerVillagerId(VillagerRegistry.java:125)

### ISSUE THREAD

**Issue by itanshi** [InfinityRaider/AgriCraft#350]
java.lang.RuntimeException
        at cpw.mods.fml.common.registry.VillagerRegistry.registerVillagerId(VillagerRegistry.java:125)
        at com.InfinityRaider.AgriCraft.init.WorldGen.init(WorldGen.java:17)
        at com.InfinityRaider.AgriCraft.AgriCraft.postInit(AgriCraft.java:100)

http://pastebin.com/7yhVMtLa

I hope you can help, thanks :)

edit: er just now noticed, is this the same issue as rftools villager conflict?
edit2: yes :/ what should I change it to?

**Comment by InfinityRaider** [comment]
Update to 1.4 pls
