### ISSUE TITLE
Crash upon updating to 1.4.0

### ISSUE THREAD

**Issue by SkullyGamingMC** [InfinityRaider/AgriCraft#408]
Upon updating Agricraft, I get this crash report from trying to load Minecraft:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 05/10/15 16:44
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: java/nio/file/Paths
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: java/nio/file/Paths
	at com.InfinityRaider.AgriCraft.utility.IOHelper.readOrWrite(IOHelper.java:58)
	at com.InfinityRaider.AgriCraft.utility.IOHelper.readOrWrite(IOHelper.java:36)
	at com.InfinityRaider.AgriCraft.handler.ConfigurationHandler.readSeedBlackList(ConfigurationHandler.java:200)
	at com.InfinityRaider.AgriCraft.utility.SeedHelper.initSeedBlackList(SeedHelper.java:29)
	at com.InfinityRaider.AgriCraft.utility.SeedHelper.init(SeedHelper.java:22)
	at com.InfinityRaider.AgriCraft.AgriCraft.postInit(AgriCraft.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more
Caused by: java.lang.ClassNotFoundException: java.nio.file.Paths
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.6.0_24, Sun Microsystems Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
	Memory: 109997408 bytes (104 MB) / 661782528 bytes (631 MB) up to 954466304 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJ	Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar) 
	UCHIJ	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
	UCHIJ	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJ	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJ	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJ	PhaseBlocks{4.1.0} [PhaseBlocks] (1.7.10-PhaseBlocks-4.1.0.jar) 
	UCHIJ	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJ	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
	UCHIJ	StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
	UCHIE	AgriCraft{1.7.10-1.4.0} [AgriCraft] (AgriCraft-1.7.10-1.4.0-1.7.10.jar) 
	UCHIJ	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJ	AlchBling{%VERSION%} [Alchemical Bling] (AlchemicalBling-1.1.1.7-universal.jar) 
	UCHIJ	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJ	arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.7.jar) 
	UCHIJ	aura{0.1r0} [Aura Cascade] (AuraCascade-538.jar) 
	UCHIJ	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) 
	UCHIJ	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHIJ	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-11.jar) 
	UCHIJ	Botania{r1.7-224} [Botania] (Botania r1.7-224.jar) 
	UCHIJ	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHIJ	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJ	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHIJ	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCHIJ	EE3HELP{2.2a} [EE3 Helper] (EE3Help-2.2a.jar) 
	UCHIJ	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.10.jar) 
	UCHIJ	EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) 
	UCHIJ	Equivalence{1.2.0} [Equivalence] (Equivalence-1.7.10-1.2.0.jar) 
	UCHIJ	evilcraft{0.8.8} [EvilCraft] (EvilCraft-1.7.10-0.8.8.jar) 
	UCHIJ	exnihilo{1.38-46} [Ex Nihilo] (Ex-Nihilo-1.38-46.jar) 
	UCHIJ	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJ	ftfloocraft{1.7.10-1.3} [Floocraft] (Floocraft-1.7.10-1.3.jar) 
	UCHIJ	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-163.jar) 
	UCHIJ	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UCHIJ	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	UCHIJ	GardenOfGlass{sqrt(-1)} [Garden of Glass] (GardenOfGlass.jar) 
	UCHIJ	ModGeochests{1.2.3} [§aGeochests] (geochests-1.7.10-v1.2.3.jar) 
	UCHIJ	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJ	HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) 
	UCHIJ	TIcarus{@VERSION@} [Icarus] (Icarus-1.0.4.jar) 
	UCHIJ	interdictionpillar{1.7.10-1.0.0} [Interdiction Pillar] (interdictionpillar-1.0.0.jar) 
	UCHIJ	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJ	LomLib{3.2.0} [LomLib] (LomLib-1.7.10-3.2.0-universal.jar) 
	UCHIJ	LookingGlass{0.2.0.00} [Looking Glass] (lookingglass-1.7.10-0.2.0.00.jar) 
	UCHIJ	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJ	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCHIJ	magicalcropsdeco{4.0.0_PUBLIC_BETA_4} [Magical Crops: Decorative] (magicalcropsdeco-4.0.0_PUBLIC_BETA_4.jar) 
	UCHIJ	lmt{B-0.1} [Lyra's Magnificent Trinkets] (MagnificentTrinkets Beta 0.1b.jar) 
	UCHIJ	Mimicry{1.7.x_1492_1.0.10} [Mimicry] (Mimicry-1.7.10_1492_1.0.10c.jar) 
	UCHIJ	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar) 
	UCHIJ	modtweaker2{0.9.2} [Mod Tweaker 2] (ModTweaker2-0.9.3.jar) 
	UCHIJ	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) 
	UCHIJ	Mystcraft{0.12.3.00} [Mystcraft] (mystcraft-1.7.10-0.12.3.00.jar) 
	UCHIJ	NaturalAbsorption{1.2.1} [Natural Absorption] (NaturalAbsorption-1.7.10-1.2.1.jar) 
	UCHIJ	necromancy{1.7.1} [Necromancy] (Necromancy-1.7.10.jar) 
	UCHIJ	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHIJ	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHIJ	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHIJ	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHIJ	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) 
	UCHIJ	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHIJ	recallstones{0.5.2} [Recall Stones] (RecallStones-1.7.10-0.5.2.jar) 
	UCHIJ	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCHIJ	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCHIJ	Sanguimancy{1.7.10-1.1.9-33} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-33.jar) 
	UCHIJ	SanguineExtras{1.3.2} [Sanguine Utilities] (Sanguine Utilities-1.3.2.jar) 
	UCHIJ	simplecondenser{1.2.0} [Simple Condensers] (Simple Condensers-1.7.10-1.2.0-universal.jar) 
	UCHIJ	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UCHIJ	StorageDrawers{1.7.10-1.5.12} [Storage Drawers] (StorageDrawers-1.7.10-1.5.12.jar) 
	UCHIJ	Tails{1.7.10-1.3.0} [Tails] (Tails-1.7.10-1.3.0.jar) 
	UCHIJ	TaintedMagic{1.1.5.7} [Tainted Magic] (TaintedMagic-1.1.5.7.jar) 
	UCHIJ	tfsimplymagic{0.2.0} [TF Simply Magic] (TFSimplyMagic0.2.0-1.7.10.jar) 
	UCHIJ	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJ	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) 
	UCHIJ	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-37.jar) 
	UCHIJ	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHIJ	thaumicinfusion{4.05} [Thaumic Infusion] (ThaumicInfusion-4.06.jar) 
	UCHIJ	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) 
	UCHIJ	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UCHIJ	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJ	VillagersNose{1.3a} [Villager's Nose] (VillagersNose-1.7.10-1.3c.jar) 
	UCHIJ	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) 
	UCHIJ	wiiemc{1.0.1} [What Is Its EMC?] (WIIEMC-1.7.10-1.0.1-universal.jar) 
	UCHIJ	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJ	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UCHIJ	aobd{2.8.1} [Another One Bites The Dust] (AOBD-2.8.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 8.15.10.2361' Renderer: 'Intel(R) HD Graphics Family'

**Comment by InfinityRaider** [comment]
What version of java are you running?
I'm suspecting you are using 1.6, but on the CurseForge page it clearly states 1.7 should be used.

**Comment by RlonRyan** [comment]
Well at least the logs say the wrong Java version is being used...

**Comment by InfinityRaider** [comment]
You're right, didn't notice. Update to 1.7
