### ISSUE TITLE
Crash after adding to pack

### ISSUE THREAD

**Issue by jatman8** [InfinityRaider/AgriCraft#427]
>old version crash log removed to avoid confusion.

**Comment by jatman8** [comment]
My appoligies, that was using an old version, the same thing happens with the latest though
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 14/10/15 10:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: diamond
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoSuchFieldError: diamond
	at codechicken.lib.inventory.InventoryUtils.actualDamage(InventoryUtils.java:35)
	at codechicken.nei.ItemStackMap$DetailMap.put(ItemStackMap.java:88)
	at codechicken.nei.ItemStackMap.put(ItemStackMap.java:227)
	at codechicken.nei.ItemStackSet.add(ItemStackSet.java:29)
	at codechicken.nei.api.API.hideItem(API.java:111)
	at com.InfinityRaider.AgriCraft.proxy.ClientProxy.hideItemInNEI(ClientProxy.java:118)
	at com.InfinityRaider.AgriCraft.compatibility.NEI.NEIConfig.hideItems(NEIConfig.java:42)
	at com.InfinityRaider.AgriCraft.compatibility.NEI.NEIConfig.loadConfig(NEIConfig.java:35)
	at com.InfinityRaider.AgriCraft.proxy.ClientProxy.initNEI(ClientProxy.java:108)
	at com.InfinityRaider.AgriCraft.compatibility.NEI.NEIHelper.postTasks(NEIHelper.java:15)
	at com.InfinityRaider.AgriCraft.compatibility.ModHelper.postInit(ModHelper.java:174)
	at com.InfinityRaider.AgriCraft.AgriCraft.postInit(AgriCraft.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 341766856 bytes (325 MB) / 1001390080 bytes (955 MB) up to 1001390080 bytes (955 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.2.1
	LaunchWrapper: 38 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: mods.immibis.microblocks.coremod.MicroblockSupporterTransformer
          - Transformer: mods.immibis.microblocks.crossmod.MicroblocksBCTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: openmods.core.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: com.olafski.fastleafdecay.FldTransformer
          - Transformer: lumien.resourceloader.asm.ClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: mods.immibis.core.impl.MultiInterfaceClassTransformer
          - Transformer: mods.immibis.core.impl.TraitTransformer
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJ	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJ	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJ	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJ	ImmibisMicroblocks{59.0.0} [Immibis's Microblocks] (Immibiss-Microblocks-Mod-1.7.10.jar) 
	UCHIJ	NotEnoughItems{1.0.4.80} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.80-universal.jar) 
	UCHIJ	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIE	AgriCraft{1.7.10-1.4.1} [AgriCraft] (AgriCraft-1.7.10-1.4.1-1.7.10 (1).jar) 
	UCHIJ	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJ	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJ	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) 
	UCHIJ	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJ	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJ	CarpentersBlocks{3.3.8_dev_r2} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r2 - MC 1.7.10.jar) 
	UCHIJ	ChickenChunks{1.3.4.18} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.18-universal.jar) 
	UCHIJ	CustomMainMenu{1.8} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.8.jar) 
	UCHIJ	D3Core{1.1.0.31} [D3Core] (D3Core-1.7.10-1.1.0.31.jar) 
	UCHIJ	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.1.1_1.7.10.jar) 
	UCHIJ	props{2.1.1} [Decocraft] (Decocraft-2.1.1_1.7.10.jar) 
	UCHIJ	enderutilities{0.4.1} [Ender Utilities] (enderutilities-1.7.10-0.4.1.jar) 
	UCHIJ	etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar) 
	UCHIJ	extrabuttons{1.7.10.1} [ExtraButtons] (ExtraButtons-1.7.10.1.jar) 
	UCHIJ	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJ	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJ	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) 
	UCHIJ	headcrumbs{1.6.2} [Headcrumbs] (Headcrumbs-1.6.2.jar) 
	UCHIJ	ImmibisCore{59.0.1} [Immibis Core] (Immibis-Core-1.7.10.jar) 
	UCHIJ	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJ	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal (1).jar) 
	UCHIJ	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJ	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJ	jacb{1.0.4} [JACB] (JACB-1.7.10-1.0.4.jar) 
	UCHIJ	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJ	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJ	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJ	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJ	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.7.10-3.0.0b43-universal.jar) 
	UCHIJ	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCHIJ	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJ	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJ	RedLogic{59.0.1} [RedLogic] (RedLogic-Mod-1.7.10.jar) 
	UCHIJ	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHIJ	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCHIJ	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCHIJ	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJ	woodstuff{1.2.1} [WoodStuff] (WoodStuff-1.2.1.jar) 
	UCHIJ	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	Mantle Environment: Environment healthy.
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by InfinityRaider** [comment]
This is 1.3.1, and the latest is 1.4.1, I'm not accepting bug reports for outdated versions sorry.

**Comment by InfinityRaider** [comment]
Seems like you posted two crash logs, noticed it after, I'll try to look at what's happening.

**Comment by InfinityRaider** [comment]
Just adding agricraft makes it crash with this crash log?

**Comment by jatman8** [comment]
So it seems what was happening is i had a delicate balance of mods that would crash if I added any more and crash if I took any away, and worlds wouldn't load at all. A quick fresh install of minecraft  and putting the same mods folder in as the broken install worked like a dream. I'm sorry for wasting your time infinityraider but at first it seemed like a problem with agricarft. Have a good day :)

**Comment by InfinityRaider** [comment]
np
