### ISSUE TITLE
NullPointerException when breaking tank

### ISSUE THREAD

**Issue by compwiz1548** [InfinityRaider/AgriCraft#524]
I've come across an interesting bug with the multiblock tanks. Using Infinity 2.2.2, I placed down a 4x4x1 tank. It was raining so the tank began to fill. A minute or so later, before the tank was full, I broke a block of the tank and my game disconnected from my server. Upon further testing, I found it to happen occasionally when breaking the bottom north west block of a tank. Here's the error that appears in my console when it disconnects.
```
[FML/]: There was a critical exception handling a packet on channel agricraft
java.lang.NullPointerException
	at com.InfinityRaider.AgriCraft.tileentity.irrigation.TileEntityTank.setFluidLevel(TileEntityTank.java:186) ~[TileEntityTank.class:?]
	at com.InfinityRaider.AgriCraft.network.MessageSyncFluidLevel$MessageHandler.onMessage(MessageSyncFluidLevel.java:51) ~[MessageSyncFluidLevel$MessageHandler.class:?]
	at com.InfinityRaider.AgriCraft.network.MessageSyncFluidLevel$MessageHandler.onMessage(MessageSyncFluidLevel.java:44) ~[MessageSyncFluidLevel$MessageHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by InfinityRaider** [comment]
What version?

**Comment by compwiz1548** [comment]
Issue was originally found in AgriCraft 1.4.5, however I've tested it in 1.4.6-hotfix and it is still happening.

**Comment by InfinityRaider** [comment]
Right, but can you give the crashlog for that version because the stacktrace doesn't match the line numbers.

**Comment by compwiz1548** [comment]
I would, however, it does not create one. It disconnects from the server with "A fatal error has occured, this connection is terminated" and then prints the above stacktrace ~30 times.

**Comment by InfinityRaider** [comment]
Give me that stacktrace, so I know what line it crashes on.

**Comment by InfinityRaider** [comment]
Actually nevermind I was looking at my 1.8.8 code, that's why the stacktrace wasn't matching. Sorry, my mistake.
