### ISSUE TITLE
SMP Problem on connect to server with minetweaker scripts

### ISSUE THREAD

**Issue by BakermanLP** [InfinityRaider/AgriCraft#627]
Hello,
I have a problem with agricraft mutations in minetweaker scripts. The script is working perfect on single player. But when I want to connect to the server I got a error message in the minetweaker.log:

ERROR: Error executing MagicalCrops.zs: null
java.lang.NullPointerException
    at com.InfinityRaider.AgriCraft.farming.mutation.MutationHandler.add(MutationHandler.java:249)
    at com.InfinityRaider.AgriCraft.compatibility.minetweaker.SeedMutation$AddAction.apply(SeedMutation.java:56)
    at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:70)
    at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:169)
    at com.InfinityRaider.AgriCraft.compatibility.minetweaker.SeedMutation.add(SeedMutation.java:29)
    at MagicalCrops.__script__(MagicalCrops.zs:103)
    at __ZenMain__.run(MagicalCrops.zs)
    at minetweaker.runtime.MTTweaker.load(MTTweaker.java:163)
    at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:673)
    at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:28)
    at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:21)

I think, that is related to the following entry in my MagicalCrops.zs file:

https://github.com/BakermanLP/ProjectRETv8/blob/8649a9f191b1ca49a572225fecf08a3f6eaf6905/scripts/MagicalCrops.zs#L103
SeedMutation.add(CoalSeeds, MinicioSeeds, seedPotato);

Also there is a longer discussion in the following issue:
https://github.com/jaredlll08/CraftTweaker/issues/11

I don't know, on which side the problem is.

Versions:
- forge 1558
- AgriCraft-1.7.10-1.5.0.jar
- CraftTweaker Latest version
- magicalcrops-4.0.0_PUBLIC_BETA_5.jar

Michael (aka BakermanLP)

**Comment by InfinityRaider** [comment]
I think this is because the server syncs the mutations to the client and here the MT script runs before that is completed. I'm not really sure how to fix this, but I have made this syncing have highest priority, this might fix it, but again I'm not sure.
When the next release is out, keep me up to speed if this still happens.
