### ISSUE TITLE
Crash with magic crops.

### ISSUE THREAD

**Issue by gazzack** [InfinityRaider/AgriCraft#632]
on place of magic crops seed on crop.

[12:14:01] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: com/mark719/magicalcrops/crops/BlockMagicalCrops
	at com.InfinityRaider.AgriCraft.utility.RenderHelper.plantIconIndex(RenderHelper.java:84) ~[RenderHelper.class:?]
	at com.InfinityRaider.AgriCraft.tileentity.TileEntityCrop.getPlantIcon(TileEntityCrop.java:245) ~[TileEntityCrop.class:?]
	at com.InfinityRaider.AgriCraft.renderers.RenderCrop.renderWorldBlock(RenderCrop.java:28) ~[RenderCrop.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530) ~[bma.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: com.mark719.magicalcrops.crops.BlockMagicalCrops
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by InfinityRaider** [comment]
what version are you using?

**Comment by InfinityRaider** [comment]
This is a very outdated version as the class where it crashes hasn't existed for ages now.
