### ISSUE TITLE
Planting Melon Seed on Sticks results in Client Crash Loop

### ISSUE THREAD

**Issue by Strikes** [InfinityRaider/AgriCraft#677]
Took a Melon Seed and attempted to put it on Crop Sticks; crashed immediately. Any attempts to load back into the game results in a crash as soon as the player loads in.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 7/17/16 10:44 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.addScaledVertexWithUV(RenderBlockBase.java:210)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.drawScaledFaceBackXZ(RenderBlockBase.java:343)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.drawScaledPrism(RenderBlockBase.java:284)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:30)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at fastcraft.ab.a(F:201)
	at fastcraft.ak.a(F:475)
	at fastcraft.HC.al(F:50)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.addScaledVertexWithUV(RenderBlockBase.java:210)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.drawScaledFaceBackXZ(RenderBlockBase.java:343)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.drawScaledPrism(RenderBlockBase.java:284)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:30)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
	at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)

-- Block Entity Details --
Details:
	Name: AgriCraft:TileEntity_crop // com.InfinityRaider.AgriCraft.tileentity.TileEntityCrop
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (453,62,-115), Chunk: (at 5,3,13 in 28,-8; contains blocks 448,0,-128 to 463,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at fastcraft.ab.a(F:201)
	at fastcraft.ak.a(F:475)
	at fastcraft.HC.al(F:50)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Strikes12'/1086, l='MpServer', x=453.10, y=64.62, z=-115.84]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-848,64,942), Chunk: (at 0,4,14 in -53,58; contains blocks -848,0,928 to -833,255,943), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Level time: 643300 game time, 229515 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntityZombie['Zombie'/1157, l='MpServer', x=510.50, y=43.00, z=-45.50], EntityChicken['Chicken'/1159, l='MpServer', x=496.14, y=67.00, z=-43.53], EntityCreeper['Creeper'/1415, l='MpServer', x=497.33, y=35.25, z=-40.41], EntityCartChest['entity.MinecartChest.name'/1301, l='MpServer', x=516.50, y=33.72, z=20.50], EntitySkeleton['Skeleton'/1178, l='MpServer', x=529.36, y=31.00, z=-58.83], EntitySkeleton['Skeleton'/1179, l='MpServer', x=532.84, y=31.00, z=-59.34], EntityCartChest['entity.MinecartChest.name'/1183, l='MpServer', x=519.50, y=35.72, z=-45.50], EntityBat['Bat'/1184, l='MpServer', x=518.88, y=32.10, z=-47.50], EntityCreeper['Creeper'/1186, l='MpServer', x=512.06, y=35.00, z=-47.59], EntitySkeleton['Skeleton'/1187, l='MpServer', x=521.21, y=58.00, z=-39.60], EntitySkeleton['Skeleton'/1188, l='MpServer', x=516.91, y=60.00, z=-42.47], EntityTrail['unknown'/551, l='MpServer', x=453.10, y=64.62, z=-115.84], EntityCartChest['entity.MinecartChest.name'/1198, l='MpServer', x=501.50, y=28.72, z=-29.53], EntitySpider['Spider'/1205, l='MpServer', x=384.16, y=63.65, z=-36.52], EntityTFNagaSegment['unknown'/183, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/184, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/185, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/186, l='MpServer', x=0.60, y=-0.24, z=0.60], EntitySkeleton['Skeleton'/1210, l='MpServer', x=377.97, y=57.35, z=-193.94], EntityTFNagaSegment['unknown'/187, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/188, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/189, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityPig['Pig'/1213, l='MpServer', x=375.34, y=64.00, z=-195.31], EntityTFNagaSegment['unknown'/190, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityTFNagaSegment['unknown'/191, l='MpServer', x=0.60, y=-0.24, z=0.60], EntitySpider['Spider'/1087, l='MpServer', x=445.69, y=16.00, z=-98.84], EntityTFNagaSegment['unknown'/192, l='MpServer', x=0.60, y=-0.24, z=0.60], EntitySkeleton['Skeleton'/1088, l='MpServer', x=454.33, y=14.24, z=-94.70], EntityCreeper['Creeper'/1216, l='MpServer', x=532.14, y=30.29, z=-39.65], EntityTFNagaSegment['unknown'/193, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityChicken['Chicken'/1089, l='MpServer', x=473.41, y=64.00, z=-88.41], EntityTFNagaSegment['unknown'/194, l='MpServer', x=0.60, y=-0.24, z=0.60], EntityBat['Bat'/1090, l='MpServer', x=456.50, y=27.10, z=-78.00], EntityChicken['Chicken'/1091, l='MpServer', x=405.53, y=62.38, z=-138.63], EntityItem['item.item.egg'/1092, l='MpServer', x=405.44, y=62.13, z=-138.59], EntitySkeleton['Skeleton'/1093, l='MpServer', x=442.89, y=29.00, z=-167.03], EntityPig['Pig'/1094, l='MpServer', x=504.72, y=63.00, z=-105.16], EntityZombie['Zombie'/1222, l='MpServer', x=533.38, y=67.00, z=-41.00], EntityZombie['Zombie'/1095, l='MpServer', x=416.00, y=37.00, z=-75.44], EntityCartChest['entity.MinecartChest.name'/1223, l='MpServer', x=548.50, y=31.72, z=-58.50], EntityCreeper['Creeper'/1096, l='MpServer', x=419.56, y=12.00, z=-169.00], EntityClientPlayerMP['Strikes12'/1086, l='MpServer', x=453.10, y=64.62, z=-115.84], EntityCreeper['Creeper'/1097, l='MpServer', x=416.56, y=36.00, z=-173.00], EntitySheep['Sheep'/1098, l='MpServer', x=482.16, y=63.00, z=-164.66], EntitySheep['Sheep'/1099, l='MpServer', x=490.94, y=62.25, z=-174.72], EntitySheep['Sheep'/1100, l='MpServer', x=488.69, y=63.00, z=-168.16], EntityChicken['Chicken'/1101, l='MpServer', x=497.94, y=63.00, z=-155.72], EntitySheep['Sheep'/1102, l='MpServer', x=498.13, y=63.00, z=-159.75], EntitySquid['Squid'/1106, l='MpServer', x=456.31, y=56.87, z=-174.82], EntityBat['Bat'/1111, l='MpServer', x=524.49, y=21.85, z=-143.30], EntityCartChest['entity.MinecartChest.name'/1367, l='MpServer', x=548.50, y=30.72, z=10.50], EntityBat['Bat'/1112, l='MpServer', x=524.25, y=34.10, z=-138.75], EntityZombie['Zombie'/1113, l='MpServer', x=407.97, y=45.00, z=-77.53], EntityWitch['Witch'/1114, l='MpServer', x=402.13, y=40.00, z=-64.53], EntitySlime['Slime'/1115, l='MpServer', x=398.22, y=22.00, z=-82.78], EntitySquid['Squid'/1116, l='MpServer', x=427.02, y=59.70, z=-177.47], EntityPig['Pig'/1118, l='MpServer', x=523.13, y=63.00, z=-85.69], EntityBat['Bat'/1119, l='MpServer', x=404.15, y=22.09, z=-49.14], EntityBat['Bat'/1120, l='MpServer', x=399.62, y=37.92, z=-63.81], EntityCreeper['Creeper'/1121, l='MpServer', x=387.63, y=26.00, z=-69.50], EntityChicken['Chicken'/1123, l='MpServer', x=395.44, y=62.57, z=-168.56], EntityHat['unknown'/483, l='MpServer', x=453.10, y=64.62, z=-115.84], EntitySkeleton['Skeleton'/1124, l='MpServer', x=403.75, y=63.00, z=-184.62], EntityCreeper['Creeper'/1125, l='MpServer', x=496.50, y=38.00, z=-58.50], EntityCreeper['Creeper'/1126, l='MpServer', x=499.50, y=38.00, z=-62.50], EntityChicken['Chicken'/1127, l='MpServer', x=509.44, y=65.00, z=-61.41], EntityChicken['Chicken'/1128, l='MpServer', x=496.11, y=64.09, z=-56.36], EntityItem['item.item.egg'/1129, l='MpServer', x=509.53, y=65.13, z=-59.88], EntitySkeleton['Skeleton'/1130, l='MpServer', x=498.22, y=64.00, z=-48.41], EntityXPOrb['Experience Orb'/1258, l='MpServer', x=380.16, y=14.25, z=-228.91], EntityChicken['Chicken'/1131, l='MpServer', x=435.61, y=65.20, z=-45.34], EntityZombie['Zombie'/1133, l='MpServer', x=531.38, y=34.00, z=-141.50], EntityChicken['Chicken'/1135, l='MpServer', x=467.49, y=63.59, z=-42.12], EntityBat['Bat'/1138, l='MpServer', x=419.11, y=24.67, z=-38.90], EntityZombie['Zombie'/1140, l='MpServer', x=427.35, y=38.65, z=-40.28], EntityPig['Pig'/1141, l='MpServer', x=381.97, y=63.00, z=-93.03], EntitySkeleton['Skeleton'/1144, l='MpServer', x=396.50, y=27.00, z=-59.50], EntityChicken['Chicken'/1145, l='MpServer', x=397.72, y=63.00, z=-184.47], EntityCreeper['Creeper'/1147, l='MpServer', x=516.44, y=36.00, z=-48.09], EntitySpider['Spider'/1276, l='MpServer', x=472.41, y=62.77, z=-46.12], EntityCreeper['Creeper'/1150, l='MpServer', x=383.50, y=63.00, z=-77.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by InfinityRaider** [comment]
minecraft version, agricraft version?

**Comment by Strikes** [comment]
1.7.10 Minecraft - Latest Agricraft 1.7.10 - 1.5.0

Worked around the issue by adding the Melons to the Blacklist.

**Comment by InfinityRaider** [comment]
Thats not really a great fix though, remove whatever mod this is :
at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)

and see if it still occurs

**Comment by Strikes** [comment]
Good Question - One of these I suppose: https://github.com/MrTJP

A slew of ProjectRed mods are loaded. (Base, Compat, Integration, Lighting, Mechanical, World)

I'll give it a try during some downtime in the server population.

**Comment by InfinityRaider** [comment]
Alright thanks, I'm not going to bother debugging if that bug doesn't happen with a clean stacktrace.

**Comment by DranKof** [comment]
@InfinityRaider 
I just tried it again after removing the MrTJP core and all the dependent mods (project red/forge locator/etc), I will upload the log as a new error I guess.

**Comment by InfinityRaider** [comment]
Alright Ill close this one then. Thanks for the clean stacktrace
