### ISSUE TITLE
Crash -- Rendering Block Entity

### ISSUE THREAD

**Issue by DranKof** [InfinityRaider/AgriCraft#687]
Running FTB Infinity 1.7.10 (2.5.0) - Fastcraft is enabled - AgriCraft{1.7.10-1.5.0}

All MrTJPCore mods ("dirty stacktrace mods in a previous issue report") were disabled including 2 ForgeRelocation core mods and all 6 ProjectRed mods that are included in the modpack.

TO REPRODUCE THE ERROR:

Place melon or pumpkin seeds (it seems the vine+block plants) in crop sticks, game crashes immediately, when world is reloaded, game crashes on vine + cropstick combo plant chunk load.

In this crash log, melon seeds were used.

---

[03:49:10] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 16-8-15 上午3:49
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
    at net.minecraft.block.Block.func_149677_c(Block.java:527)
    at com.InfinityRaider.AgriCraft.renderers.PlantRenderer.renderStemPlant(PlantRenderer.java:169)
    at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantStem.renderPlantInCrop(CropPlantStem.java:60)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.renderPlant(RenderCrop.java:60)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:46)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at fastcraft.ab.a(F:201)
    at fastcraft.ak.a(F:475)
    at fastcraft.HC.al(F:50)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.Block.func_149677_c(Block.java:527)
    at com.InfinityRaider.AgriCraft.renderers.PlantRenderer.renderStemPlant(PlantRenderer.java:169)
    at com.InfinityRaider.AgriCraft.farming.cropplant.CropPlantStem.renderPlantInCrop(CropPlantStem.java:60)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.renderPlant(RenderCrop.java:60)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderCrop.doWorldRender(RenderCrop.java:46)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.renderBlock(RenderBlockBase.java:80)
    at com.InfinityRaider.AgriCraft.renderers.blocks.RenderBlockBase.func_147500_a(RenderBlockBase.java:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)

-- Block Entity Details --
Details:
    Name: AgriCraft:TileEntity_crop // com.InfinityRaider.AgriCraft.tileentity.TileEntityCrop
    Block type: ID #229 (tile.agricraft:crops // com.InfinityRaider.AgriCraft.blocks.BlockCrop)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-3,65,-8), Chunk: (at 13,4,8 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #229 (tile.agricraft:crops // com.InfinityRaider.AgriCraft.blocks.BlockCrop)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at fastcraft.ab.a(F:201)
    at fastcraft.ak.a(F:475)
    at fastcraft.HC.al(F:50)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['DranKof'/87, l='MpServer', x=-3.54, y=66.62, z=-8.86]]
    Chunk stats: MultiplayerChunkCache: 3784, 3784
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 3947 game time, 3947 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 4 total; [EntityTrail['unknown'/128, l='MpServer', x=-3.54, y=66.62, z=-8.86], EntityClientPlayerMP['DranKof'/87, l='MpServer', x=-3.54, y=66.62, z=-8.86], EntityHat['unknown'/102, l='MpServer', x=-3.54, y=66.62, z=-8.86], EntityItem['item.tile.cactus'/26, l='MpServer', x=29.19, y=61.13, z=-2.16]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by InfinityRaider** [comment]
Reopened.

**Comment by InfinityRaider** [comment]
In the config there is a setting to change the crop rendering, what is that set too?

**Comment by DranKof** [comment]
rendering {
    B:"Crop rendering setting"=true
}

On my client, it says **true**. I will ask what the server does to see if it matches, too, as the comment says that it should.

**Comment by DranKof** [comment]
Update on the problem:
The others were able to chunkload and then /setblock the tile, apparently it was a pumpkin plant that resulted from crossbreeding carrots and potatoes.
