### ISSUE TITLE
Crash rendering item in new build

### ISSUE THREAD

**Issue by Eufranio** [InfinityRaider/AgriCraft#764]
**Steps to reproduce:**
1. Open an Crafting Station or Crafting Table
2. Put an ingot there (that will give an AgriCraft's nugget as output)
2. Profit, crash!

```
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:79)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.onStartDrawingQuadsCall(TessellatorBakedQuad.java:68)
	at com.infinityraider.infinitylib.render.tessellation.TessellatorAbstractBase.startDrawingQuads(TessellatorAbstractBase.java:88)
	at com.infinityraider.infinitylib.render.item.BakedInfItemModel.func_188616_a(BakedInfItemModel.java:54)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:160)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:227)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:266)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146977_a(GuiMultiModule.java:229)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:96)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:332)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)```
Full crash-report: https://hastebin.com/epofohegey.pas

**Comment by InfinityRaider** [comment]
Thanks for reporting, I'll have to investigate, because this should not be possible.

**Comment by Eufranio** [comment]
That's the pack I'm running: http://www.technicpack.net/modpack/magibeta-pack.940049

**Comment by InfinityRaider** [comment]
I am not able to reproduce, remove cclib and try it then please.

**Comment by Eufranio** [comment]
I am, even after removing CodeChickenLib, the same crash.

**Comment by Eufranio** [comment]
I only updated InfinityLib, forgot about AgriCraft, sorry for the trouble, it's fixed now! 😄

**Comment by InfinityRaider** [comment]
Great!
