### ISSUE TITLE
Redstone toggle for irrigation canal thing.

### ISSUE THREAD

**Issue by jamesfhj** [InfinityRaider/AgriCraft#769]
I placed a redstone togglable irrigation canal, the one made with a lever, a channel, and an iron bar. It immidiately crashed my game. I have the Crash Report if needed.

**Comment by InfinityRaider** [comment]
Yes it is needed.

**Comment by jamesfhj** [comment]
I made a post before and was told to put crash reports in the pastebin, but I have no idea where that is... I'm not overly familiar with all the ins and outs of github. So, for now I'll post it here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.1-66.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 12/27/16 4:41 AM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at com.infinityraider.agricraft.renderers.blocks.RenderChannelValve.renderSide(RenderChannelValve.java:63)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWoodChannel(RenderChannel.java:37)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWorldBlockWoodStatic(RenderChannel.java:142)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWorldBlockWoodStatic(RenderChannel.java:25)
	at com.infinityraider.agricraft.renderers.blocks.RenderBlockCustomWood.renderWorldBlockStatic(RenderBlockCustomWood.java:45)
	at com.infinityraider.agricraft.renderers.blocks.RenderBlockCustomWood.renderWorldBlockStatic(RenderBlockCustomWood.java:28)
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:64)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:135)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.infinityraider.agricraft.renderers.blocks.RenderChannelValve.renderSide(RenderChannelValve.java:63)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWoodChannel(RenderChannel.java:37)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWorldBlockWoodStatic(RenderChannel.java:142)
	at com.infinityraider.agricraft.renderers.blocks.RenderChannel.renderWorldBlockWoodStatic(RenderChannel.java:25)
	at com.infinityraider.agricraft.renderers.blocks.RenderBlockCustomWood.renderWorldBlockStatic(RenderBlockCustomWood.java:45)
	at com.infinityraider.agricraft.renderers.blocks.RenderBlockCustomWood.renderWorldBlockStatic(RenderBlockCustomWood.java:28)
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:64)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:135)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:86)

-- Block model being tesselated --
Details:
	Block: agricraft:water_channel_valve[channel_east=false,channel_north=false,channel_south=false,channel_west=false,powered=false]
	Block location: World: (170,66,265), Chunk: (at 10,4,9 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)

-- Block being tesselated --
Details:
	Block type: ID #225 (tile.agricraft:water_channel_valve // com.infinityraider.agricraft.blocks.irrigation.BlockWaterChannelValve)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (170,66,265), Chunk: (at 10,4,9 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ReallyBIGDoor'/850, l='MpServer', x=169.27, y=63.00, z=265.02]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,256), Chunk: (at 8,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 325250 game time, 468513 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 18 total; [EntityPig['Pig'/51, l='MpServer', x=112.87, y=74.00, z=260.50], EntityPig['Pig'/54, l='MpServer', x=113.96, y=74.00, z=260.48], EntityPig['Pig'/64845, l='MpServer', x=106.34, y=73.00, z=252.79], EntityPig['Pig'/64846, l='MpServer', x=102.81, y=73.00, z=253.75], EntityPlayerSP['ReallyBIGDoor'/850, l='MpServer', x=169.27, y=63.00, z=265.02], EntityPig['Pig'/340, l='MpServer', x=184.68, y=69.00, z=281.42], EntityPig['Pig'/89, l='MpServer', x=129.51, y=81.00, z=254.22], EntityZombie['Zombie'/67169, l='MpServer', x=173.50, y=32.00, z=256.91], EntityPig['Pig'/373, l='MpServer', x=225.71, y=72.00, z=292.51], EntityPig['Pig'/374, l='MpServer', x=223.75, y=72.00, z=344.65], EntityPig['Pig'/147, l='MpServer', x=165.50, y=69.00, z=216.70], EntityPig['Pig'/404, l='MpServer', x=238.55, y=72.00, z=264.72], EntityPig['Pig'/406, l='MpServer', x=226.78, y=72.00, z=344.84], EntityPig['Pig'/407, l='MpServer', x=226.02, y=72.00, z=343.90], EntitySkeleton['Skeleton'/66202, l='MpServer', x=161.51, y=38.00, z=281.22], EntityPig['Pig'/426, l='MpServer', x=235.36, y=72.00, z=261.29], EntityPig['Pig'/175, l='MpServer', x=163.50, y=68.00, z=225.32], EntityPig['Pig'/244, l='MpServer', x=186.55, y=69.00, z=281.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 418751656 bytes (399 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D1 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.4.0} [InfinityLib] (infinitylib-0.4.0.jar) 
	UCHIJAAAA	agricraft{2.0.0-0.4.0-a5} [AgriCraft] (agricraft-2.0.0-0.4.0-a5.jar) 
	UCHIJAAAA	Quark{r1.1-66} [Quark] (Quark-r1.1-66.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJAAAA	JEI{3.13.6.391} [Just Enough Items] (jei_1.10.2-3.13.6.391.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.0.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	refinedstorage{1.2.14} [Refined Storage] (refinedstorage-1.2.14.jar) 
	UCHIJAAAA	rftools{5.58} [RFTools] (rftools-1.10-5.58.jar) 
	UCHIJAAAA	simplebarrels{1.25h} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25h.jar) 
	UCHIJAAAA	spartanshields{1.0} [Spartan Shields] (SpartanShields-1.10.2-1.0.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.1-66.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor 
	OptiFine Version: OptiFine_1.10.2_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13456 Compatibility Profile Context 21.19.164.1
	OpenGlRenderer: AMD Radeon R7 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by InfinityRaider** [comment]
Tx, has been fixed.

Btw for the next time pls use pastebin to share huge amounts of text.

**Comment by VT-14** [comment]
Pastebin is another website.

Github has a similar feature.  A "Gist" which you can access via the link at the top of these pages.
