### ISSUE TITLE
Error breaking Wooden Irrigation Channel

### ISSUE THREAD

**Issue by Eufranio** [InfinityRaider/AgriCraft#775]
```
[20:24:04] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntityChannel.hasNeighbourCheck(Lnet/minecraft/util/EnumFacing;)Z
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntityChannel.hasNeighbourCheck(Lnet/minecraft/util/EnumFacing;)Z
        at com.infinityraider.agricraft.blocks.irrigation.AbstractBlockWaterChannel.func_176221_a(AbstractBlockWaterChannel.java:44) ~[AbstractBlockWaterChannel.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:410) ~[art$a.class:?]
        at net.minecraft.world.WorldServer.createSnapshot(WorldServer.java:981) ~[ls.class:?]
        at org.spongepowered.api.world.extent.Extent.createSnapshot(Extent.java:196) ~[Extent.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.api.world.Location.createSnapshot(Location.java:640) ~[Location.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:229) ~[PacketUtil.class:1.10.2-2171-5.1.0-BETA-2010]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) ~[PacketUtil.class:1.10.2-2171-5.1.0-BETA-2010]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) ~[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by cha0s** [comment]
Same here :( Major bug, it still exists even if I go to creative, break it, and then right click it with an empty hand. It's still there.

This is on 1.10.2

**Comment by RlonRyan** [comment]
I believe this issue to be fixed.

**Comment by InfinityRaider** [comment]
yup

**Comment by Eufranio** [comment]
So, where can I download the version with the fix, is it available?

**Comment by InfinityRaider** [comment]
not yet
