### ISSUE TITLE
Error killing farmer villager

### ISSUE THREAD

**Issue by Eufranio** [InfinityRaider/AgriCraft#776]
```
[20:26:48] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_111]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_111]
        at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.getCareer(VillagerRegistry.java:226) ~[VillagerRegistry$VillagerProfession.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_145748_c_(EntityVillager.java:736) ~[zn.class:?]
        at net.minecraft.util.EntityDamageSource.func_151519_b(SourceFile:47) ~[ri.class:?]
        at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:105) ~[rg.class:?]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:433) ~[SpongeCommonEventFactory.class:1.10.2-2171-5.1.0-BETA-2010]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:248) ~[sf.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:502) ~[zn.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:507) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:577) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:644) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:136) ~[PacketUtil.class:1.10.2-2171-5.1.0-BETA-2010]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:39) ~[fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by RlonRyan** [comment]
Which version?

**Comment by RlonRyan** [comment]
@InfinityRaider is this fixed already? Didn't you do something with the villager code recently?

**Comment by Eufranio** [comment]
AgriCraft 2.0.0-0.4.0-a5
InfinityLib 0.4.0
Sorry for the late reply =/

**Comment by TehNut** [comment]
I think it's fixed in the dev-growth branch. Dunno if you've released since that was merged

**Comment by RlonRyan** [comment]
Assuming this to be fixed. Please do reopen this issue if it shows up again in the upcoming releases.
