### ISSUE TITLE
java.lang.ClassCastException on placing sprinkler to irrigation block

### ISSUE THREAD

**Issue by Protheus** [InfinityRaider/AgriCraft#778]
Game crash when placing an irrigation channel to a sprinkler block. Game crashed immediately when loading the worls again. had to remove the mod to get game back online.

MC: 1.10.2
Agricraft: agricraft-2.0.0-0.4.0-a5
Infinitylib: infinitylib-0.4.0
No optifine is used
Game crash on with and without foamfix (Law): foamfix-0.5.0-BETA2-law

**Game crash when placing a irrigation to a sprinkler block:**
http://pastebin.com/CbfwxFcc

**Game crash when reloading the world:**
http://pastebin.com/fUCW7yvk

**Short:**
Description: Rendering Block Entity
java.lang.ClassCastException: com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntitySprinkler cannot be cast to com.infinityraider.agricraft.blocks.tiles.TileEntityCustomWood
    at com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntityChannel.hasNeighbourCheck(TileEntityChannel.java:164)
    at com.infinityraider.agricraft.blocks.irrigation.BlockWaterChannel.func_180640_a(BlockWaterChannel.java:94)
    at com.infinityraider.agricraft.blocks.irrigation.BlockWaterChannel.func_180646_a(BlockWaterChannel.java:75)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
    at net.minecraft.pathfinding.PathWorldListener.func_184378_a(SourceFile:60)
    at net.minecraft.pathfinding.PathWorldListener.func_184376_a(SourceFile:25)
    at net.minecraft.world.World.func_184138_a(World.java:415)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:363)
    at net.minecraft.world.World.func_180501_a(World.java:349)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:165)
    at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:463)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Going back to a previous version:
- Agricraft: agricraft-2.0.0-i0.3.0-a3
- Infinitylib: infinitylib-0.3.0

**Game crash with following error:**
http://pastebin.com/cQ7dFraG

**Comment by RlonRyan** [comment]
Should have used the world helper class here... That would have fixed it.
