### ISSUE TITLE
[1.10.2] Server crash at village

### ISSUE THREAD

**Issue by gdude2002** [InfinityRaider/AgriCraft#806]
Forge: 12.18.3.2202
Agricraft: 2.0.0-0.5.0-a6
Infinitylib: 1.10.2-0.4.0

---

One of my users was exploring, and happened upon a village. The server now crashes whenever that area is loaded:

```java
Description: Ticking block entity

java.lang.NoClassDefFoundError: com/infinityraider/infinitylib/utility/WorldHelper
	at com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntityChannel.checkConnections(TileEntityChannel.java:117)
	at com.infinityraider.agricraft.blocks.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:147)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.infinityraider.infinitylib.utility.WorldHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: java.lang.NullPointerException
```

**Comment by gdude2002** [comment]
Attempting this with the newer infinitylib (0.5.0), but the mod should pin to the correct version

**Comment by gdude2002** [comment]
Looks good with latest InfinityLib. I guess I should've checked - please pin versions :3
