### ISSUE TITLE
Craft - Nugget DataValue

### ISSUE THREAD

**Issue by lagonnebula** [InfinityRaider/AgriCraft#823]
Hi, it's seem that ai make it crash everytime.

I made a /give Pseudo agricraft:agri_nugget 1 12 
And it's seem that the nugget with datavalue 12 didn't exist, i got the message in chat.
But now when i drop nugget on the ground or i click it in my inventory i got a crash server.

> Time: 1/30/17 5:59 AM
Description: Rendering screen
java.lang.ArrayIndexOutOfBoundsException: 12
	at com.infinityraider.agricraft.items.ItemNugget.func_77667_c(ItemNugget.java:39)
	at net.minecraft.item.Item.func_77657_g(Item.java:291)
	at net.minecraft.item.Item.func_77653_i(Item.java:361)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:507)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:569)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by RlonRyan** [comment]
Fixed. Thanks for reporting. I forgot to account for invalid item metas, given that I forgot about commands allowing for the setting of wrong metas.
