### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by bookerthegeek** [InfinityRaider/AgriCraft#869]
```
[01:54:59] [Client thread/INFO] [AgriCraft-Plugins]: [AGRI-DEBUG]: 
Failed to load AgriPlugin
	Of class: com.infinityraider.agricraft.compat.waila.WailaPlugin!
	For annotation: com.infinityraider.agricraft.api.AgriPlugin!
	As Instanceof: com.infinityraider.agricraft.api.IAgriPlugin!
[01:54:59] [Client thread/WARN] [FML]: ****************************************
[01:54:59] [Client thread/WARN] [FML]: * Dangerous alternative prefix `minecraft` for name `farmer.agricraft`, expected `agricraft` invalid registry invocation/invalid name?
[01:54:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:82)
[01:54:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:90)
[01:54:59] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.<init>(VillagerRegistry.java:206)
[01:54:59] [Client thread/WARN] [FML]: *  at com.infinityraider.agricraft.entity.villager.EntityVillagerFarmer.<clinit>(EntityVillagerFarmer.java:29)
[01:54:59] [Client thread/WARN] [FML]: *  at com.infinityraider.agricraft.init.AgriEntities.lambda$new$0(AgriEntities.java:21)
[01:54:59] [Client thread/WARN] [FML]: *  at com.infinityraider.infinitylib.entity.EntityRegistryEntry.register(EntityRegistryEntry.java:137)...
[01:54:59] [Client thread/WARN] [FML]: ****************************************
```

Thought you should know.
* agricraft-2.0.0-0.7.0-a12.jar

**Comment by RlonRyan** [comment]
"Fixed" by removing AgriCraft villagers for now.
